Repository team-4-rolling/rolling, pull requests merged in 2025-02, with the labels that each got.

#33 [Feat] Toast2기능 추가
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/api/api.jsx
  src/assets/icons/check.svg
  src/assets/icons/close.svg
  src/components/common/Button/Button.jsx
  src/components/common/Button/Button.style.jsx
  src/components/common/Toast/Toast.jsx
  src/components/common/Toast/Toast.style.jsx
Labels: Feat

#36 [Feat] 개별 메시지 삭제, 롤링페이퍼 자체 삭제기능
  .gitignore
  package-lock.json
  package.json
  src/api/messages.api.jsx
  src/api/recipient.api.jsx
  src/pages/RollingPage/Messages.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
  src/router.jsx
  vercel.json
Labels: Feat

#38 [Feat] Emoji
  .gitignore
  package-lock.json
  package.json
  src/api/reactions.jsx
  src/components/Emoji/Emoji.jsx
  src/components/Emoji/Emoji.styles.jsx
  src/components/Emoji/Icons.jsx
  src/components/Emoji/Icons.styles.jsx
  src/components/common/Header/SecondHeader.jsx
  src/components/common/Header/SecondHeader.styles.jsx
  src/pages/RollingPage/RollingPage.jsx
Labels: Feat

#39 [Feat] create Skeleton with Lazy, Suspense
  .gitignore
  src/api/recipient.api.jsx
  src/pages/RollingPage/Messages.data.jsx
  src/pages/RollingPage/Messages.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
  src/pages/RollingPage/Skeleton/Skeleton.jsx
  src/pages/RollingPage/Skeleton/Skeleton.style.jsx
Labels: Feat

#41 [Style] Landing page 반응형
  src/components/common/Button/Button.style.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.styles.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/LandingPage.styles.jsx
Labels: Style

#42 [Feat] Scroll up button
  package-lock.json
  src/assets/icons/white.arrow.svg
  src/pages/RollingPage/Messages.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
Labels: Feat

#43 [Style] 버튼 스타일 추가조정
  package-lock.json
  src/assets/icons/arrow.svg
  src/components/common/Button/Button.style.jsx
Labels: Style

#45 [Style] 버튼 스타일 추가조정
  src/components/common/Button/Button.style.jsx
Labels: Style

#46 [Refactor] create getRecipientById api & delete find method
  package-lock.json
  src/api/recipient.api.jsx
  src/pages/RollingPage/RollingPage.jsx
Labels: Refactor

#47 [Fix] Input 수정
  src/components/common/Input/Input.jsx
  src/pages/FromPage/FromPage.jsx
Labels: fix

#48 [Feat] Topage
  src/api/toPageData.jsx
  src/assets/icons/select.svg
  src/pages/ToPage/SelectableBox.jsx
  src/pages/ToPage/ToPage.jsx
  src/pages/ToPage/ToPage.styles.jsx
  src/router.jsx
Labels: Feat

#50 [Fix] header exception handling
  src/assets/icons/cat.jpeg
  src/components/common/Header/Header.jsx
Labels: fix

#54 [Style] Topage 반응형과 toast 추가
  src/api/toPageData.jsx
  src/pages/ToPage/Form.jsx
  src/pages/ToPage/SelectableBox.jsx
  src/pages/ToPage/ToPage.jsx
  src/pages/ToPage/ToPage.styles.jsx
Labels: Style

#55 [Style] post page button 반응형 오류 수정
  src/components/common/Select/Select.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
Labels: Style

#58 [Refactor] - rollingpage 리팩토링
  src/api/recipient.api.jsx
  src/components/common/Select/Select.style.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
  src/pages/RollingPage/Skeleton/Skeleton.style.jsx
Labels: Refactor

#59 [Feat] List page
  src/api/recipientsApi.jsx
  src/components/ListCard/Listcard.jsx
  src/components/ListCard/Listcard.style.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.style.jsx
Labels: Feat

#61 [Feat] show Modalpopup on clicking delete paper button & message card
  src/components/common/Modal/ModalContent/ModalContent.jsx
  src/components/common/Modal/ModalContent/ModalContent.styles.jsx
  src/components/common/Modal/ModalContent/PaperDelete.jsx
  src/hooks/useWindow.jsx
  src/pages/RollingPage/Messages.data.jsx
  src/pages/RollingPage/RollingPage.jsx
Labels: Feat

#64 [Feat] 공유하기 버튼 ( URL 복사 공유 및 카카오톡 공유기능 추가 )
  index.html
  src/components/SelectableBox/SelectableBox.jsx
  src/components/ShareButton/ShareButton.jsx
  src/components/common/Header/SecondHeader.jsx
  src/components/common/Header/SecondHeader.styles.jsx
  src/pages/ToPage/Form.jsx
  src/pages/ToPage/ToPage.jsx
Labels: Feat

#65 [Refactor] create global constants
  src/api/messages.api.jsx
  src/api/recipient.api.jsx
  src/components/ModalContent/ModalContent.jsx
  src/components/ModalContent/ModalContent.styles.jsx
  src/components/ModalContent/PaperDelete.jsx
  src/components/Skeleton/Skeleton.jsx
  src/components/Skeleton/Skeleton.style.jsx
  src/components/common/Modal/ModalContent/PaperDelete.jsx
  src/components/common/Select/Select.style.jsx
  src/constants/messageConstants.jsx
  src/pages/RollingPage/Messages.data.jsx
  src/pages/RollingPage/Messages.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
Labels: Refactor

#66 [Feat & Fix] Header
  package-lock.json
  package.json
  src/components/CircleImages/CircleImages.jsx
  src/components/CircleImages/Loading/CircleImgLoading.jsx
  src/components/CircleImages/Loading/CircleImgLoading.styles.jsx
  src/components/Emoji/Icons.jsx
  src/components/Skeleton/Skeleton.style.jsx
  src/components/common/Header/Header.styles.jsx
  src/components/common/Header/SecondHeader.jsx
  src/components/common/Header/SecondHeader.styles.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/zustand/rollingPageLoading.js
Labels: Feat

#68 [Chore & Style]landing page style & message constants
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/LandingPage.styles.jsx
Labels: Style

#70 [Feat] useLockScroll
  src/hooks/useLockScroll.js
Labels: Feat

#71 [Refactor] 리스트 카드 모듈화
  src/components/ListCard/ArrowButton.jsx
  src/components/ListCard/ListSwiper.jsx
  src/components/ListCard/Listcard.jsx
  src/components/ListCard/RecipientCard.jsx
Labels: Refactor

#72 [Feat] Modal
  package-lock.json
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/Modal.styles.jsx
Labels: Feat

#75 [Fix] Sharebutton 카카오 오류수정
  src/components/ShareButton/ShareButton.jsx
Labels: fix

#76 [Refactor] Refactoring infinite Scroll & scrollup button with intersection observer
  src/components/common/Select/Select.style.jsx
  src/pages/RollingPage/RollingPage.jsx
Labels: Refactor, Feat

#77 [Style] 토스트 반응형 추가
  src/App.jsx
  src/components/common/Toast/Toast.jsx
  src/components/common/Toast/Toast.style.jsx
  src/styles/GlobalStyle.jsx
Labels: Style

#78 [Fix] ListPage 의 정상화
  src/components/ListCard/ArrowButton.jsx
  src/components/ListCard/ListSwiper.jsx
  src/components/ListCard/Listcard.jsx
Labels: fix

#81 [Chore] API
  .eslintrc.js
  src/api/images.api.jsx
  src/api/messages.api.jsx
  src/api/reactions.api.jsx
  src/api/recipient.api.jsx
  src/api/recipientsApi.jsx
  src/api/toPageData.jsx
  src/components/Emoji/Emoji.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ToPage/ToPage.jsx
Labels: Chore

#82 [Chore] edit vercel.json
  vercel.json
Labels: Chore

#83 [Fix] Sharebutton 카카오 공유 코드수정
  src/components/ShareButton/ShareButton.jsx
  src/components/ShareButton/ShareButton.styles.jsx
Labels: fix

#84 [Style] edit padding-top , overflow-x
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
Labels: Style

#85 [Style] Theme
  index.html
  src/styles/GlobalStyle.jsx
  src/styles/theme.jsx
Labels: Style

#86 [Feat] ListPage 스켈레톤 구현
  src/components/ListCard/Listcard.style.jsx
  src/components/ListCard/SkeletonCardList.jsx
  src/components/ListCard/SkeletonList.style.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.style.jsx
Labels: Refactor, Feat, Style

#87 [Feat] From page
  package-lock.json
  package.json
  src/api/images.api.jsx
  src/api/messages.api.jsx
  src/components/Editor/Editor.jsx
  src/components/Editor/Editor.styles.jsx
  src/components/ModalContent/ModalContent.jsx
  src/components/Profile/Loading/ProfileLoading.jsx
  src/components/Profile/Loading/ProfileLoading.styles.jsx
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.styles.jsx
  src/components/RollingCard/RollingCard.jsx
  src/components/RollingCard/RollingCard.styles.jsx
  src/pages/FromPage/FromPage.jsx
  src/pages/FromPage/FromPage.styles.jsx
  vite.config.js
Labels: Feat

#89 [Style] 리스트 페이지 수정
  src/components/ListCard/Listcard.style.jsx
  src/pages/ListPage/ListPage.style.jsx
Labels: Style

#90 [Style & Fix] from page
  src/components/Editor/Editor.styles.jsx
  src/components/ModalContent/ModalContent.styles.jsx
  src/components/Profile/Profile.styles.jsx
  src/components/RollingCard/RollingCard.styles.jsx
  src/components/common/Select/Select.jsx
  src/components/common/Select/Select.style.jsx
  src/pages/FromPage/FromPage.jsx
  src/pages/FromPage/FromPage.styles.jsx
Labels: Style, fix

#91 [Feat, Fix] Topage의 SelectableBox에 Skeleton기능 추가
  src/components/SelectableBox/SelectableBox.jsx
  src/components/SelectableBox/SkeletonBox.jsx
  src/components/SelectableBox/SkeletonBox.styles.jsx
  src/pages/ToPage/Form/Form.jsx
  src/pages/ToPage/ToPage.jsx
Labels: Feat, fix

#92 [Chore] lading page changes images
  src/assets/icons/emoji.png
  src/assets/icons/image.png
Labels: Chore

#94 [Style] README.md
  README.md
Labels: Style
