Repository team-4-rolling/rolling, pull requests merged in 2025-01, with the labels that each got.

#5 [chore] color Object 추가
  package-lock.json
  package.json
  src/App.jsx
  src/styles/theme.jsx
Labels: Docs

#6 [ Feat] create Select
  package-lock.json
  src/assets/icons/PlusIcon.svg
  src/assets/icons/arrowClose.svg
  src/assets/icons/arrowOpen.svg
  src/components/common/Select/SelectDropDown.jsx
  src/components/common/Select/SelectStyle.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/router.jsx
Labels: Feat

#8 [Feat]Header
  index.html
  src/assets/icons/cat.jpeg
  src/assets/icons/logo.svg
  src/assets/icons/share.svg
  src/assets/icons/smile.svg
  src/components/CircleImages/CircleImages.jsx
  src/components/CircleImages/CircleImages.styles.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.styles.jsx
  src/components/common/Header/SecondHeader.jsx
  src/components/common/Header/SecondHeader.styles.jsx
  src/components/common/Line/Line.jsx
Labels: Feat

#12 [Feat] post card UI
  index.html
  src/assets/icons/trash.svg
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.styles.jsx
  src/components/PostCardUl/PostCardUl.jsx
  src/components/PostCardUl/PostCardUl.styles.jsx
  src/styles/GlobalStyle.jsx
Labels: Feat

#9 Button
  package-lock.json
  src/components/common/Button/Button.jsx
Labels: Feat

#17 [Feat] create Rolling page - infinite scroll , dynamic rendering with useParams
  package-lock.json
  package.json
  src/api/api.jsx
  src/components/PostCardUl/PostCardUl.jsx
  src/components/PostCardUl/PostCardUl.styles.jsx
  src/components/common/Select/Select.jsx
  src/components/common/Select/Select.style.jsx
  src/components/common/Select/SelectDropDown.jsx
  src/pages/FromPage/FromPage.jsx
  src/pages/RollingPage/Mesages.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
  src/pages/ToPage/ToPage.jsx
  src/router.jsx
Labels: Feat

#18 [Feat]모달창 구현
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/Modal.styles.jsx
  src/pages/LandingPage/LandingPage.jsx
Labels: Feat

#23 [Feat] landing page
  src/assets/icons/emoji.png
  src/assets/icons/image.png
  src/components/common/Button/Button.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/LandingPage.styles.jsx
Labels: Feat

#26 [Feat] Input
  src/components/common/Input/Input.jsx
  src/components/common/Input/Input.style.jsx
Labels: Feat

#28 [Style] rolling page card responsive css
  package-lock.json
  package.json
  src/components/RollingCard/RollingCard.jsx
  src/components/RollingCard/RollingCard.styles.jsx
  src/pages/RollingPage/Mesages.jsx
Labels: Style

#29 [Style] RollingPage 반응형
  src/api/api.jsx
  src/components/RollingCard/RollingCard.jsx
  src/pages/RollingPage/Mesages.jsx
  src/pages/RollingPage/Messages.jsx
  src/pages/RollingPage/RollingPage.jsx
  src/pages/RollingPage/RollingPage.style.jsx
  src/router.jsx
  src/styles/theme.jsx
Labels: Style

#32 [Style] font face 수정
  public/font/Pretendard-Bold.woff2
  public/font/Pretendard-Regular.woff2
  src/styles/GlobalStyle.jsx
  src/styles/theme.jsx
Labels: Style

#35 [Feat]Header
  src/api/api.jsx
  src/components/CircleImages/CircleImages.jsx
  src/components/CircleImages/CircleImages.styles.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.styles.jsx
  src/components/common/Header/SecondHeader.jsx
  src/components/common/Header/SecondHeader.styles.jsx
  src/pages/RollingPage/RollingPage.jsx
Labels: Feat
